.TH LSV1.5.0 1 "October 2025" "v1.5.0" "Colorized Output"
.SH NAME
lsv1.5.0 - colorize file names based on file type
.SH SYNOPSIS
.B lsv1.5.0
.SH DESCRIPTION
Adds color output using ANSI escape codes to distinguish file types:
.TP
Blue - Directories
.TP
Green - Executables
.TP
Red - Archives (.tar, .gz, .zip)
.TP
Pink - Symbolic Links
.TP
Reverse Video - Special files
.SH AUTHOR
Uzair Tariq
.SH VERSION
v1.5.0 - Colorized Output
